---
title: "Assignments"
---

This page describes details about the weekly (in-class + homework) assignments and the final project that are required in PSY 511.

## Weekly assignments

#### Week 1 (due 2017-01-16 at start of class)

1. Choose one of the verification bias examples from *Flawed Science*(http://pubman.mpdl.mpg.de/pubman/item/escidoc:1569964:8/component/escidoc:1569966/Stapel_Investigation_Final_report.pdf). In a paragraph or two, propose ways you might avoid this sort of bias in your own research.
2. Choose one of the TOP guideline categories where either your own research practices have room to improve or you are doing rather well. In a paragraph or two, explain your reasoning.
3. In a paragraph or two, describe your current knowlege of R and at least three learning goals you have for building upon it.

- Use a sensible file name: psy511-anaya-2016-01-09-write-up.pdf

## Final project

Each student will produce a final project and demo or report upon it during one of the last two class periods in the semester. The specific project topic will be determined in consultation with the instructor. Here are some possible topics for students to consider:

- Reuse/reanalysis of existing published dataset
- Research project website and workflow
- Draft of a data paper suitable for submission to a data journal
- Tutorial on reproducible research practices
- Develop mTurk/jsPsych/psiTurk study and analysis workflow