---
title: "Shiny"
---

## Shiny

- RStudio framework for making interactive, web-based data applications
- Basic [tutorial](http://shiny.rstudio.com/tutorial/)
- [Gallery](http://shiny.rstudio.com/)

## Components

- User interface (UI)
- Server instructions
- Web server
- Web browser

## Template

~~~~
library(shiny)
ui <- fluidPage()
server <- function(input, output) {}
shinyApp(ui = ui, server = server)
~~~~

## Correlation demo

- Goal: Create an app to visualize the effects of changing the slope (m) and error (sd) in a linear relation $Y \sim X * \beta + N(0,\sigma)$
- Inputs
    + number of points
    + slope
    + error
- Outputs
    + scatter plot with fitted line
    + correlation value

## UI input components

- Sliders for numeric input use `sliderInput()` function
- Parameters *inputId*, *label*, *min*, *max*, and *value*

~~~
sliderInput(inputId = "points",
  label = "Number of points:",
  min = 10,
  max = 200,
  value = 50)
~~~

## Sliders for slope, error

~~~
sliderInput(inputId = "slope",
  label = "Slope:",
  min = -10,
  max = 10,
  value = 1)
      
sliderInput(inputId = "error",
  label = "Error:",
  min = .0001,
  max = 5,
  value = 0.5)
~~~

## UI output `scatter.smooth` plot

- Just a placeholder for plot.
- Make the plot in the `server` function

~~~~
plotOutput("scatterPlot")
~~~~

## Server function

- Syntax is `server <- function(input, output) {}`
- Use `input$points`, `input$slope`, and `input$error` to grab values from UI
- Save plot to `output$scatterPlot`

## Calculating points and plotting them

- Generate n = `input$points` as x
- Calculate y = x * `input$slope` + error
    + where error = `rnorm(input$points, sd = input$error)`
- Plot x, y

~~~
output$scatterPlot <- renderPlot({
    # Calculate x, y, with slope and error
    x = runif(input$points)
    
    # Vectorize x for point-wise multiplication
    y = rep(input$slope, input$points) * as.vector(x) + 
        rnorm(input$points, sd = input$error)
        
    # draw the histogram with the specified number of bins
    scatter.smooth(x = x, y = y, xlab = "x", ylab = "y")
})
~~~

## The whole shebang

```{r}
library(shiny)

# Define UI for application that draws a histogram
ui <- fluidPage(
   
   # Application title
   titlePanel("Correlation Demo"),
   
   # Sidebar with a slider input for number of points 
   sidebarLayout(
      sidebarPanel(
         sliderInput(inputId = "points",
                     label = "Number of points:",
                     min = 10,
                     max = 200,
                     value = 50),
         sliderInput(inputId = "slope",
                     label = "Slope:",
                     min = -10,
                     max = 10,
                     value = 1),
         sliderInput(inputId = "error",
                     label = "Error:",
                     min = .0001,
                     max = 5,
                     value = 0.5)
      ),
      
      # Show a plot of the generated distribution
      mainPanel(
         plotOutput(outputId = "scatterPlot")
      )
   )
)

# Define server logic
server <- function(input, output) {
   
   output$scatterPlot <- renderPlot({
     
    # Calculate x, y, with slope and error
     x = runif(input$points)
     y = rep(input$slope, input$points) * as.vector(x) + rnorm(input$points, sd = input$error)
      
    # draw the plot
    scatter.smooth(x = x, y = y, xlab = "x", ylab = "y")
   })
}

# Run the application 
shinyApp(ui = ui, server = server)
```

## Why do this?

- Fun, informative way to **simulate** your data analysis pipeline and visualization path **before** you run your study
- Strong hypothesis generation, prediction
- How to wrangle your data into a form you can analyze