---
title: "2017-04-01-repositories"
author: "Rick O. Gilmore"
date: '`r Sys.time()`'
output:
  ioslides_presentation:
    css: ../css/gilmore-ioslides.css
    incremental: no
    self-contained: yes
    transition: default
    widescreen: yes
  html_document:
    code_folding: hide
    keep_md: yes
    self_contained: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
  github_document: default
  pdf_document:
    latex_engine: xelatex
    toc: yes
    toc_depth: 2
bibliography: ../bib/reproducibility.bib
---

## Today's topics

- Where to share?
- Publishing data, open access
- Your open science profile

# Where to share?

## Considerations for storing

- Why are you doing this?
    - For yourself
    - For colleagues
    - For funders/journals
- What are you planning to share/store?
- What permissions do you have?
    - From participants
    - From colleagues/collaborators
    - From IRB/ethics boards
    
## Considerations for using/reusing

- What information do I want?
- How do I find it?
- How do I access it?

## [Inter-university Consortium for Political and Social Research (ICPSR)](https://www.icpsr.umich.edu/icpsrweb/)

- Data repository
- More than 50 year history of storing, sharing data
- Based at U Michigan
- Dominant player in sociology, demography, political science
- Search by measure
- Some online analyses

---

<iframe src="https://www.icpsr.umich.edu/icpsrweb/">
</iframe>

<div class="centered">
<https://www.icpsr.umich.edu/icpsrweb/>
</div>

## [Data Dryad](http://datadryad.org/)

- Focus on data linked to publications
- Strong presence in biological sciences, but not domain-specific

---

<iframe src="http://datadryad.org/">
</iframe>

<div class="centered">
<http://datadryad.org/>
</div>

## [Dataverse](http://dataverse.org)

- Domain general repository + software for repositories
- Institute for Quantitative Social Sciences at Harvard

---

<iframe src="http://dataverse.org/">
</iframe>

<div class="centered">
<http://dataverse.org/>
</div>

## [Databrary](http://databrary.org)

- Specialized for video
- Emphasizing developmental science
- Search for data

---

<iframe src="http://databrary.org">
</iframe>

<div class="centered">
<http://databrary.org>
</div>

## [Open Science Framework](http://osf.io)

- Product of the [Center for Open Science (COS)](http://cos.io)
- Domain general "hub" for research workflows
- Home of [PsyArXiv](https://osf.io/preprints/psyarxiv) preprints

---

<iframe src="http://osf.io">
</iframe>

<div class="centered">
<http://osf.io>
</div>

## [PSU's ScholarSphere](https://scholarsphere.psu.edu/)

- Institutional repository
- Domain general, linked to individual scholars

---

<iframe src="https://scholarsphere.psu.edu/">
</iframe>

<div class="centered">
<https://scholarsphere.psu.edu/>
</div>

## [National Database for Autism Research (NDAR)](https://ndar.nih.gov/)

- Now the NIMH data archive
- Data aggregation, secondary analyses
- Details about measures, individual participants

---

<iframe src="https://ndar.nih.gov/">
</iframe>

<div class="centered">
<https://ndar.nih.gov/>
</div>

## TalkBank/CHILDES

- Language transcripts, audio, video

---

<iframe src="http://talkbank.org/">
</iframe>

<div class="centered">
<http://talkbank.org/>
</div>

## WordBank

- Repository of one type of measure: MacArthur-Bates Communicative Development Inventory (M-CDI)

---

<iframe src="http://wordbank.stanford.edu/">
</iframe>

<div class="centered">
<http://wordbank.stanford.edu/>
</div>

## Other options

- Personal/lab website
- GitHub

## [Data.World](http://data.world)

- Social network for shared data

---

<iframe src="http://data.world">
</iframe>

# Publishing data

- [Nature Scientific Data](http://www.nature.com/sdata/)
- [APA's Archives of Scientific Psychology](http://www.apa.org/pubs/journals/arc/index.aspx)
- COS contemplating a new journal
- [Transparency and Openness Promotion (TOP) guidelines](https://cos.io/top/)

# Your open science portfolio

## Should do

- [ORCID](http://orcid.org/)
- non-PSU email for professional use

## Might do

- GitHub, Twitter 
- yourname.com
- [ResearchGate](http://researchgate.net)
- [Academia.edu](http://academia.edu)

# Funder policies
    
## NSF

*"Investigators are expected to share with other researchers, at no more than incremental cost and within a reasonable time, the primary data, samples, physical collections and other supporting materials created or gathered in the course of work under NSF grants. Grantees are expected to encourage and facilitate such sharing."*

<https://www.nsf.gov/bfa/dias/policy/dmp.jsp>

## NIMH

*"The National Institute of Mental Health (NIMH) has established an informatics infrastructure to enable the sharing and use of data collected from human subjects in clinical research by the entire research community.  Researchers funded by NIMH are strongly encouraged to deposit data from human subjects into this infrastructure.  In addition, non-NIMH funded researchers with related data are welcome to deposit their data."*

<https://grants.nih.gov/grants/guide/notice-files/NOT-MH-15-012.html>

## References {.smaller}