2017-02-13
================
Rick O. Gilmore
2017-03-26

<!-- Lecture -->
Today's topics
--------------

-   Some observations about GitHub use and R Markdown
-   Simulation as a tool for reproducible and transparent science
-   Visualization tools in R

Observations about GitHub use
-----------------------------

-   You're in charge of what goes where.
-   Public repos are public, but no one knows what you're doing unless you alert them.
    -   If you create a repo in your own account, add `rogilmore` or other collaborators to use the `@rogilmore` type at-mentions feature.
    -   Files you create in `https://github.com/psu-psych-511-2017-spring` I can already comment on.

Observations about GitHub use
-----------------------------

-   Pull requests are when you edit my code and want me to "pull"/adopt it.
    -   If I'm a collaborator on the project with `write` privileges, I don't have to issue a pull request.

Observations about R Markdown
-----------------------------

-   Ok to make multiple R Markdown files
-   Make sure to add spaces where they belong: `##Header` vs. `## Header`
-   Comments! Add them. This is your record of what you did.
-   Don't forget you can hide things

Be a risk-taker; be your own professor
--------------------------------------

-   <http://www.stat.cmu.edu/~cshalizi/rmarkdown>
-   <http://stat545.com/bit006_github-browsability-wins.html>

Simulation as a tool for reproducible and transparent science
-------------------------------------------------------------

-   Why simulate
-   What to simulate
-   How to simulate

Why & what to simulate?
-----------------------

-   Explore sample sizes, effect sizes, power
-   Pre-plan/test, polish data-munging workflows
-   Make hypotheses even more explicit
    -   Simulation == Pregistration on steroids
    -   '~~X affects Y~~' -&gt; 'Mean(X) &gt; Mean(Y)'
    -   or 'Mean(X) &gt;= 2\*Mean(Y)'
-   Simulate data analysis in advance

------------------------------------------------------------------------

-   Plan data visualizations in advance
-   Avoid avoidable errors
-   Plan your work, work your plan
-   Super easy to run analyses when your data come in

How to simulate
---------------

-   R functions
-   R Markdown document(s)

Super-simple example
--------------------

-   Hypothesis 1: Height (inches) is correlated with weight (lbs)

``` r
# choose sample size
sample.n <- 200

# choose intercept and slope
beta0 <- 36   # inches
beta1 <- 0.33  # Rick's guess

# choose standard deviation for error
sigma <- 10 # Rick's guess
```

------------------------------------------------------------------------

``` r
# random weights between 80 lbs and 250 lbs (uniform sampling)
w <- runif(n = sample.n, min = 80, max = 250)

h.pred <- rep(x = beta0, n = sample.n) + beta1 * w
h <- h.pred + rnorm(n = sample.n, mean = 0, sd = sigma)
```

<!-- Code to make scrolling slides -->
<style>
slides > slide { overflow: scroll; }
slides > slide:not(.nobackground):before {
  background: none;
  }
slides > slide:not(.nobackground):after {
  content: '';
  background: none;
  }
}
</style>

------------------------------------------------------------------------

``` r
library(ggplot2)
library(dplyr)
```

    ## 
    ## Attaching package: 'dplyr'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     filter, lag

    ## The following objects are masked from 'package:base':
    ## 
    ##     intersect, setdiff, setequal, union

``` r
hist(w)
```

![](2017-02-13_files/figure-markdown_github/plot-hist-1.png)

``` r
hist(h)
```

![](2017-02-13_files/figure-markdown_github/plot-hist-2.png)

``` r
hist(h.pred)
```

![](2017-02-13_files/figure-markdown_github/plot-hist-3.png)

------------------------------------------------------------------------

``` r
# Put h and w into data frame for ggplot
height.weight <- data.frame(inches = h, lbs = w)

# Plot
scatter.1 <- ggplot(data = height.weight) +
  aes(x = lbs, y = inches) +
  geom_point()
scatter.1
```

![](2017-02-13_files/figure-markdown_github/plot-scatter-1.png)

That's synthesis, now analysis
------------------------------

-   Remember Hypothesis 1: Height (inches) is correlated with weight (lbs)?

``` r
# Could use the raw data
# cor.test(x = w, y = h)
# Or, to use the values in the data frame, use with(...)

with(height.weight, cor.test(x = inches, y = lbs))
```

    ## 
    ##  Pearson's product-moment correlation
    ## 
    ## data:  inches and lbs
    ## t = 24.532, df = 198, p-value < 2.2e-16
    ## alternative hypothesis: true correlation is not equal to 0
    ## 95 percent confidence interval:
    ##  0.8283935 0.8980941
    ## sample estimates:
    ##      cor 
    ## 0.867438

Aside: extracting the statistics to make an interactive report
--------------------------------------------------------------

``` r
# Save output as a variable
cor.test.inches.lbs <- with(height.weight, cor.test(x = inches, y = lbs))

# What sort of beast is this?
mode(cor.test.inches.lbs)
```

    ## [1] "list"

------------------------------------------------------------------------

``` r
# Aha, it's a list, this shows me all of the parts
unlist(cor.test.inches.lbs)
```

    ##                            statistic.t 
    ##                     "24.5323089333243" 
    ##                           parameter.df 
    ##                                  "198" 
    ##                                p.value 
    ##                 "6.12303768245573e-62" 
    ##                           estimate.cor 
    ##                    "0.867438003143277" 
    ##                 null.value.correlation 
    ##                                    "0" 
    ##                            alternative 
    ##                            "two.sided" 
    ##                                 method 
    ## "Pearson's product-moment correlation" 
    ##                              data.name 
    ##                       "inches and lbs" 
    ##                              conf.int1 
    ##                    "0.828393508096068" 
    ##                              conf.int2 
    ##                    "0.898094087218937"

``` r
# Looks like the t value is the first element
cor.test.inches.lbs[[1]]
```

    ##        t 
    ## 24.53231

------------------------------------------------------------------------

The Pearson's product-moment correlation correlation between height and weight is 0.867, *t*(198)=24.532, *p*=0.00000, with a 95% confidence interval of \[0.828, 0.898\].

<span class="blue">I did some formatting to make the numbers look pretty.</span>

`sprintf("%.3f", my.var)` limits `my.var` to 3 decimal places; where `sprintf("%2.3f", my.var)` limits it to 2 digits to the left and 3 to the right.

Now back to analysis with our synthetic data
--------------------------------------------

``` r
fit <- lm(formula = inches ~ lbs, data = height.weight)
summary(fit) # Use lm() command to fit formula
```

    ## 
    ## Call:
    ## lm(formula = inches ~ lbs, data = height.weight)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -31.6040  -6.0684   0.5775   6.8052  22.0200 
    ## 
    ## Coefficients:
    ##             Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept) 33.76661    2.49683   13.52   <2e-16 ***
    ## lbs          0.34702    0.01415   24.53   <2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 9.805 on 198 degrees of freedom
    ## Multiple R-squared:  0.7524, Adjusted R-squared:  0.7512 
    ## F-statistic: 601.8 on 1 and 198 DF,  p-value: < 2.2e-16

``` r
(ci <- confint(fit)) # confint() command fits confidence intervals
```

    ##                  2.5 %     97.5 %
    ## (Intercept) 28.8428166 38.6904085
    ## lbs          0.3191276  0.3749182

Surrounding `(ci <- confint(fit))` in parentheses saves variable ci and prints it out.

How'd we do?
------------

| Parameter | Actual | Low Estimate | High Estimate |
|-----------|--------|--------------|---------------|
| *β*0      | 36     | 28.8428166   | 38.6904085    |
| *β*1      | 0.33   | 0.3191276    | 0.3749182     |

-   Why off on the slope (*β*1)
-   Random error, probably. Could run again.

------------------------------------------------------------------------

    ## 
    ## Call:
    ## lm(formula = inches ~ lbs, data = height.weight)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -30.7064  -5.7080   0.3121   6.0914  25.9899 
    ## 
    ## Coefficients:
    ##             Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept) 33.15441    2.49962   13.26   <2e-16 ***
    ## lbs          0.34365    0.01507   22.81   <2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 10.06 on 198 degrees of freedom
    ## Multiple R-squared:  0.7243, Adjusted R-squared:  0.7229 
    ## F-statistic: 520.2 on 1 and 198 DF,  p-value: < 2.2e-16

    ##                  2.5 %     97.5 %
    ## (Intercept) 28.2251138 38.0837126
    ## lbs          0.3139332  0.3733581

------------------------------------------------------------------------

| Parameter | Actual | Low Estimate | High Estimate |
|-----------|--------|--------------|---------------|
| *β*0      | 36     | 28.2251138   | 38.0837126    |
| *β*1      | 0.33   | 0.3139332    | 0.3733581     |

Simulation of fMRI data
-----------------------

-   Critical review: Welvaert, M., & Rosseel, Y. (2014). A Review of fMRI Simulation Studies. PLOS ONE, 9(7), e101953. <https://doi.org/10.1371/journal.pone.0101953>.
-   Welvaert, M., Durnez, J., Moerkerke, B., Berdoolaege, G. & Rosseel, Y. (2011). neuRosim: An R Package for Generating fMRI Data. Journal of Statistical Software, 44(10). Retrieved from <https://www.jstatsoft.org/article/view/v044i10>
-   AFNI's *AlphaSim*, <https://afni.nimh.nih.gov/pub/dist/doc/program_help/AlphaSim.html>

Visualization in R
==================

Plot first, analyze last
------------------------

> -   Why?
> -   [Mike Meyer](https://www.linkedin.com/in/mike-meyer-0056578a) told me so
> -   Less biased
> -   Easier to be transparent and reproducible
> -   Want/need to plot eventually anyway
> -   If a picture's worth a thousand words...
> -   How?

How
---

-   Base graphics
    -   `plot(x,y)` `hist(x)`, `coplot()`
-   `ggplot2`
    -   Grammar of graphics

Base graphics
-------------

-   Try it, maybe you'll like it
-   `plot()` takes many types of input
-   So does `summary()`
-   A little harder to customize

Data visualization with ggplot2
-------------------------------

Wickham, H. & Grolemund, G. (2017). *R for Data Science*. O'Reilly. <http://r4ds.had.co.nz/>

Let's just walk through the data visualiation chapter
-----------------------------------------------------

<http://r4ds.had.co.nz/data-visualisation.html>

Other ggplot2 resources
-----------------------

-   Wickham, H. (2010). *ggplot2: Elegant Graphics for Data Analysis (Use R!)* <http://ggplot2.org/book/>
-   ggplot2 2.1.0 documentation: <http://docs.ggplot2.org/current/>
