2017-01-30
================
Rick O. Gilmore
2017-02-08

Today's topics
--------------

-   Pregistration and registered reports
    -   What, why, who, how?
-   Introduction to [RStudio](http://rstudio.com)
-   Introduction to R Markdown

Registered reports
------------------

-   What are they?
-   Why are they a thing?
-   Who's doing them?
-   How they work and how to get involved

What are they?
--------------

-   Peer review and provisional acceptance of methodologically sound study proposals

Why registered reports?
-----------------------

-   Results (positive or null) don't determine publication (prevent publication bias)
-   Reduce questionable practices
    -   p-hacking
    -   HARKing

Why [**not**](http://www.cogsci.nl/blog/miscellaneous/215-the-pros-and-cons-of-pre-registration-in-fundamental-research) registered reports
-------------------------------------------------------------------------------------------------------------------------------------------

-   Restrict creativity in reporting "un-registered"/exploratory analyses?
    -   Clearer communication about confirmatory vs. exploratory
-   Mandatory vs. optional
-   Clinical trials vs. fundamental research
-   Exploration is not a dirty word

Who's doing them?
-----------------

-   [Journals with Registered Reports](https://cos.io/rr/#journals) from COS

------------------------------------------------------------------------

-   [*Cognition & Emotion*](http://explore.tandfonline.com/page/beh/pcem-registered-reports-of-replication-studies/)
-   [*Cortex*](http://cdn.elsevier.com/promis_misc/PROMIS%20pub_idt_CORTEX%20Guidelines_RR_29_04_2013.pdf)
-   [*Nature Human Behavior*](http://www.nature.com/nathumbehav/about/content)

How do they work
----------------

-   Google sheet comparing features <https://docs.google.com/spreadsheets/d/1D4_k-8C_UENTRtbPzXfhjEyu3BfLxdOsn9j-otrO870/edit#gid=0>

------------------------------------------------------------------------

<a href="https://www.elsevier.com/editors-update/story/peer-review/cortexs-registered-reports"> <img src="https://www.elsevier.com/__data/assets/image/0017/143162/Registered-Reports_EditorialPipeline.jpg" height=500px/> </a>

Preregistration separate from publication
-----------------------------------------

<iframe width="560" height="315" src="https://www.youtube.com/embed/SWkqdNppL-s" frameborder="0" allowfullscreen>
</iframe>
[Center for Open Science (COS) Preregistration Challenge](https://cos.io/our-services/prereg/)
----------------------------------------------------------------------------------------------

-   1,000 $1K awards, July 1, 2017 (100), January 1, 2018 (100), July 1, 2018 (250), December 31, 2018 (500)
-   Preregister [hypothesis, sampling, analysis plans](https://osf.io/zwkqj/?_ga=1.163745855.1251838540.1458403228) with OSF

[AsPredicted.org](https://aspredicted.org/)
-------------------------------------------

-   Standardized preregistration tool
-   Separate confirmatory from exploratory analyses
-   One author completes checklist, others receive email to approve
-   Unique (private) URL to pdf
-   Share when you like or never

Your thoughts on preregistration, registered reports?
-----------------------------------------------------

Tools for reproducible workflows
================================

[RStudio](http://rstudio.com)
-----------------------------

-   An integrated development environment (IDE) for R

Components of RStudio
---------------------

-   Code editor
-   R console
-   Integrated help
-   Image viewer
-   Integration with git and other version-control packages
-   Project management

RStudio in the cloud
--------------------

-   RStudio can be run in a browser from a server running RStudio Server
-   [Demo](http://ec2-52-90-103-156.compute-1.amazonaws.com/)
    -   Running this under Amazon Web Services (AWS) free tier
-   Instructions for doing this yourself can be found [here](http://strimas.com/r/rstudio-cloud-1/)

R Markdown
----------

-   [Markdown](https://daringfireball.net/projects/markdown/)
    -   Mark-up language to make it easy to write HTML
-   R Markdown special type of Markdown
    -   Allows for "literate" programming, mixing text, analysis, figures
    -   Adds to Markdown syntax

[Markdown](https://daringfireball.net/projects/markdown) syntax
---------------------------------------------------------------

-   Text formatting
    -   *italics* by surrounding text with single asterisks or underscores: `*italics*` or `_italics_`
    -   **boldface** by surrounding text with double asterisks or underscores: `**boldface**` or `__boldface__`
    -   ~~strikethrough~~ by surrounding text with double tildes: `~~strikethrough~~`
    -   [Clickable URLs](http://www.psu.edu) by surrounding link text with square brackets and URL with parentheses: `[Clickable URLs](http://www.psu.edu)`

Markdown syntax
---------------

-   Paragraph formatting
    -   Headings with level specified by the number of hash (\#) marks
    -   Lists (bullet and enumerated)
    -   Block quotes
    -   Code blocks

------------------------------------------------------------------------

    # This is a Heading 1
    ## This is a Heading 2
    ### This is a Heading 3

------------------------------------------------------------------------

-   An item
    -   A nested item
        -   A doubly-nested item
-   Another item

Code:

    - An item
        - A nested item
            - A doubly-nested item
    - Another item

------------------------------------------------------------------------

1.  An enumerated item
    -   A nested item

2.  A second enumerated item

Code:

    1. An enumerated item
        - A nested item
    1. A second enumerated item

Notice how the numbers are incremented automatically!

------------------------------------------------------------------------

> Four score and seven years ago, some famous President spoke infamous words that would live on throughout history. These words are famous enough that I want to highlight them with a block quote.

    > Four score and seven years ago, some famous President 
    > spoke infamous words that would live on throughout history.
    > These words are famous enough that I want to highlight them with a block quote.

More on Markdown syntax
-----------------------

-   Images can be inserted using this syntax `![Alt text](/path/to/img.jpg)`
-   Comments -- won't print in rendered output -- `<!- This is a comment ->`

R Markdown additions
--------------------

-   .Rmd extension
-   Combine text, code, images, figures, video
-   "Computable" reports, documents, slide shows, notebooks
-   Output in multiple formats from the same file

Make some data
--------------

``` r
x = rnorm(n = 100, mean = 0, sd = 1)   # N(0,1)
y = rnorm(n = 100, mean = 2, sd = 0.5) # N(2, 0.5)
```

Summary of x, y
---------------

``` r
summary(x)
```

    ##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ## -3.2080 -0.6230  0.2382  0.1186  0.8846  2.1970

``` r
summary(y)
```

    ##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##  0.8468  1.6420  2.1230  2.0710  2.4260  3.5420

Histogram of x
--------------

``` r
hist(x)
```

![](2017-01-30_files/figure-markdown_github/unnamed-chunk-3-1.png)

Histogram of y
--------------

``` r
hist(y)
```

![](2017-01-30_files/figure-markdown_github/unnamed-chunk-4-1.png)

Embed figure saved locally using HTML
-------------------------------------

`<img src="../img/my-img.jpg" height=500px>`

Height parameter (or, e.g. `width=800px`) is optional, but useful. Remember Markdown -&gt; HTML.

------------------------------------------------------------------------

<img src="../img/my-img.jpg" height=500px>

Embed figure from the web
-------------------------

`<img src="http://cdn.abclocal.go.com/content/wpvi/images/cms/280434_1280x720.jpg" width=900px>`

------------------------------------------------------------------------

<img src="http://cdn.abclocal.go.com/content/wpvi/images/cms/280434_1280x720.jpg" width=900px>

Embed YouTube video
-------------------

`<iframe width="420" height="315" src="https://www.youtube.com/embed/9hUy9ePyo6Q" frameborder="0" allowfullscreen></iframe>`

-   YouTube gives you code to cut and paste.

------------------------------------------------------------------------

<iframe width="420" height="315" src="https://www.youtube.com/embed/9hUy9ePyo6Q" frameborder="0" allowfullscreen>
</iframe>
Printing computed variables
---------------------------

``` r
summ.x = summary(x)
summ.y = summary(y)
names(summ.x) # Figure out variable names for indexing
```

    ## [1] "Min."    "1st Qu." "Median"  "Mean"    "3rd Qu." "Max."

------------------------------------------------------------------------

*Index by variable name:* X lies within the range of \[-3.208, 2.197\].

*Index by numeric index:* The (y-x) difference in means is `1.9524`.

*Calculate and report:* The correlation between x and y is -0.1444795.

Questions?
----------
