---
title: "2017-02-13-displays"
author: "Rick O. Gilmore"
date: "`r Sys.time()`"
output:
  ioslides_presentation:
    css: ../css/gilmore-ioslides.css
    incremental: no
    self-contained: yes
    transition: default
    widescreen: yes
  html_document:
    keep_md: yes
    self_contained: yes
  pdf_document:
    latex_engine: xelatex
    toc: yes
    toc_depth: 2
bibliography: ../bib/reproducibility.bib
---

## Today's topics

- Old business
    + Optimal workflow
- New business
    + Reproducible data-gathering
    
## Optimal workflow

- Edit local files
- Test local files
- Commit local files

- Push version to GitHub
- Raise issue

## Tools for reproducible data-gathering

- [E-Prime](https://www.pstnet.com/eprime.cfm)
- Matlab ([Psychophysics Toolbox](http://psychtoolbox.org/))
- [PsychoPy](http://www.psychopy.org/).
- [jsPsych](http://www.jspsych.org/)
- [MTurk](https://www.mturk.com/mturk/welcome)
    + [psiTurk](https://psiturk.org/)

## E-Prime

- Windows only
- [System for Teaching Experimental Psychology (STEP)](http://step.psy.cmu.edu/)
    - [[@macwhinney_stepsystem_2001]](http://doi.org/10.3758/BF03195379)
    - STEP script libraries: <http://step.psy.cmu.edu/scripts-plus/> and <http://step.psy.cmu.edu/scripts-student/>
- University of Kent script libraries: <https://www.kent.ac.uk/psychology/technical/experiments.html>

## [Psychophysics Toolbox](http://psychtoolbox.org/)

- Matlab-based
- Runs on Linux, Windows, Mac OS X
- Script libraries:
    - <http://www.kehinger.com/PTBexamples.html>
    - Introduction to Psychtoolbox on Matlab, <http://www.jonaskaplan.com/psych599.php>
- YouTube tutorial channel: <https://www.youtube.com/watch?v=5Sskr9m-UtQ>

## [PsychoPy](http://www.psychopy.org/)

- Python-based
- Runs on Linux, Windows, Mac OS X
- Script libraries:
    - [PyHab](https://github.com/jfkominsky/PyHab) for habituation/looking time studies.

## [jsPsych](http://www.jspsych.org/)

- JavaScript (js)-based
- Runs in browser, locally or via the web

## [MTurk](https://www.mturk.com/mturk/welcome)

- Amazon's system for matching workers "turkers" with tasks
- Demographics of user base
    - <http://demographics.mturk-tracker.com/#/gender/all>
- [LookIt](https://lookit.mit.edu/), looking time studies using web cameras
    - See also [[@tran_online_2017]](http://doi.org/10.1016/j.jecp.2016.12.003)
- [psiTurk](https://psiturk.org/)
    - [Experiment exchange](https://psiturk.org/ee/)
    
## [Shiny](https://github.com/daattali/shinyforms)

<iframe src="https://daattali.com/shiny/mimic-google-form/">
</iframe>

## Challenges to reproducibility

- Commercial vs. non-commercial tools
- Computers vary, OS vary, versions change
- Hard to ensure scripts run on different hardware, software
- Desktop-based (better timing) vs. web-based (less hardware/software dependent)
- Programming practices vary

## Challenges to reproducibility

- Citing resources is inconsistent
    - Resource Identification Initiative's Research Resource Identifiers (RRIDs)
    - <https://www.force11.org/group/resource-identification-initiative>
    - [[@vasilevsky_reproducibility_2013]](http://doi.org/10.7717/peerj.148)
- Terminology for tasks is inconsistent
    - Poldrack's [*Cognitive Atlas*](http://www.cognitiveatlas.org/tasks/a)
    
## Partial solutions

- Open code sharing
    + <https://github.com/gilmore-lab/peep-II>
    + <https://github.com/gilmore-lab/planforms>
- Share videos, stills of displays
    + [[@gilmore-adolph-video-2017]](http://http://osf.io/3kvp7)
    + e.g., [[@https://doi.org/10.17910/B7.272]](https://doi.org/10.17910/B7.272)
- Use Open Science Framework (OSF) or Databrary as a project "hub"
- Future: "containerize" experiment apps
    + [Docker.com](https://www.docker.com/)
    
## References